  caffe2_py2_cuda9_0_cudnn7_ubuntu16_04_build:
    environment:
      BUILD_ENVIRONMENT: "caffe2-py2-cuda9.0-cudnn7-ubuntu16.04-build"
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda9.0-cudnn7-ubuntu16.04:248"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_cuda9_0_cudnn7_ubuntu16_04_test:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda9.0-cudnn7-ubuntu16.04:248"
      USE_CUDA_DOCKER_RUNTIME: "1"
      BUILD_ENVIRONMENT: "caffe2-py2-cuda9.0-cudnn7-ubuntu16.04-test"
    resource_class: gpu.medium
    <<: *caffe2_linux_test_defaults

  caffe2_cmake_cuda9_0_cudnn7_ubuntu16_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda9.0-cudnn7-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-cmake-cuda9.0-cudnn7-ubuntu16.04-build"
    <<: *caffe2_linux_build_defaults

  caffe2_cmake_cuda9_0_cudnn7_ubuntu16_04_test:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda9.0-cudnn7-ubuntu16.04:248"
      USE_CUDA_DOCKER_RUNTIME: "1"
      BUILD_ENVIRONMENT: "caffe2-cmake-cuda9.0-cudnn7-ubuntu16.04-test"
    resource_class: gpu.medium
    <<: *caffe2_linux_test_defaults

  caffe2_py2_cuda9_1_cudnn7_ubuntu16_04_build:
    environment:
      BUILD_ENVIRONMENT: "caffe2-py2-cuda9.1-cudnn7-ubuntu16.04-build"
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda9.1-cudnn7-ubuntu16.04:248"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_cuda9_1_cudnn7_ubuntu16_04_test:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda9.1-cudnn7-ubuntu16.04:248"
      USE_CUDA_DOCKER_RUNTIME: "1"
      BUILD_ENVIRONMENT: "caffe2-py2-cuda9.1-cudnn7-ubuntu16.04-test"
    resource_class: gpu.medium
    <<: *caffe2_linux_test_defaults

  caffe2_py2_mkl_ubuntu16_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-mkl-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-mkl-ubuntu16.04-build"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_mkl_ubuntu16_04_test:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-mkl-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-mkl-ubuntu16.04-test"
    resource_class: large
    <<: *caffe2_linux_test_defaults

  caffe2_py2_gcc4_8_ubuntu14_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-gcc4.8-ubuntu14.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-gcc4.8-ubuntu14.04-build"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_gcc4_8_ubuntu14_04_test:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-gcc4.8-ubuntu14.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-gcc4.8-ubuntu14.04-test"
    resource_class: large
    <<: *caffe2_linux_test_defaults

  caffe2_onnx_py2_gcc5_ubuntu16_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-gcc5-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-onnx-py2-gcc5-ubuntu16.04-build"
    <<: *caffe2_linux_build_defaults

  caffe2_onnx_py2_gcc5_ubuntu16_04_test:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-gcc5-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-onnx-py2-gcc5-ubuntu16.04-test"
    resource_class: large
    <<: *caffe2_linux_test_defaults

  caffe2_py2_cuda8_0_cudnn7_ubuntu16_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda8.0-cudnn7-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-cuda8.0-cudnn7-ubuntu16.04-build"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_cuda8_0_cudnn7_ubuntu16_04_test:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda8.0-cudnn7-ubuntu16.04:248"
      USE_CUDA_DOCKER_RUNTIME: "1"
      BUILD_ENVIRONMENT: "caffe2-py2-cuda8.0-cudnn7-ubuntu16.04-test"
    resource_class: gpu.medium
    <<: *caffe2_linux_test_defaults

  caffe2_py2_gcc4_9_ubuntu14_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-gcc4.9-ubuntu14.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-gcc4.9-ubuntu14.04-build"
      BUILD_ONLY: "1"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_clang3_8_ubuntu16_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-clang3.8-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-clang3.8-ubuntu16.04-build"
      BUILD_ONLY: "1"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_clang3_9_ubuntu16_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-clang3.9-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-clang3.9-ubuntu16.04-build"
      BUILD_ONLY: "1"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_clang7_ubuntu16_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-clang7-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-clang7-ubuntu16.04-build"
      BUILD_ONLY: "1"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_android_ubuntu16_04_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-android-ubuntu16.04:248"
      BUILD_ENVIRONMENT: "caffe2-py2-android-ubuntu16.04-build"
      BUILD_ONLY: "1"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_cuda9_0_cudnn7_centos7_build:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda9.0-cudnn7-centos7:248"
      BUILD_ENVIRONMENT: "caffe2-py2-cuda9.0-cudnn7-centos7-build"
    <<: *caffe2_linux_build_defaults

  caffe2_py2_cuda9_0_cudnn7_centos7_test:
    environment:
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda9.0-cudnn7-centos7:248"
      USE_CUDA_DOCKER_RUNTIME: "1"
      BUILD_ENVIRONMENT: "caffe2-py2-cuda9.0-cudnn7-centos7-test"
    resource_class: gpu.medium
    <<: *caffe2_linux_test_defaults

  caffe2_py2_ios_macos10_13_build:
    environment:
      BUILD_ENVIRONMENT: caffe2-py2-ios-macos10.13-build
      BUILD_IOS: "1"
      PYTHON_INSTALLATION: "system"
      PYTHON_VERSION: "2"
    <<: *caffe2_macos_build_defaults

  caffe2_py2_system_macos10_13_build:
    environment:
      BUILD_ENVIRONMENT: caffe2-py2-system-macos10.13-build
      PYTHON_INSTALLATION: "system"
      PYTHON_VERSION: "2"
    <<: *caffe2_macos_build_defaults

