      # Pytorch linux builds
      - pytorch_linux_trusty_py2_7_9_build
      - pytorch_linux_trusty_py2_7_9_test:
          requires:
            - pytorch_linux_trusty_py2_7_9_build
      - pytorch_linux_trusty_py2_7_build
      - pytorch_linux_trusty_py2_7_test:
          requires:
            - pytorch_linux_trusty_py2_7_build
      - pytorch_linux_trusty_py3_5_build
      - pytorch_linux_trusty_py3_5_test:
          requires:
            - pytorch_linux_trusty_py3_5_build
      - pytorch_linux_trusty_py3_6_gcc4_8_build
      - pytorch_linux_trusty_py3_6_gcc4_8_test:
          requires:
            - pytorch_linux_trusty_py3_6_gcc4_8_build
      - pytorch_linux_trusty_py3_6_gcc5_4_build
      - pytorch_linux_trusty_py3_6_gcc5_4_test:
          requires:
            - pytorch_linux_trusty_py3_6_gcc5_4_build
      - pytorch_linux_trusty_py3_6_gcc7_build
      - pytorch_linux_trusty_py3_6_gcc7_test:
          requires:
            - pytorch_linux_trusty_py3_6_gcc7_build
      - pytorch_xla_linux_trusty_py3_6_gcc5_4_build:
          filters:
            branches:
              only:
                - master
      - pytorch_xla_linux_trusty_py3_6_gcc5_4_test:
          filters:
            branches:
              only:
                - master
          requires:
            - pytorch_xla_linux_trusty_py3_6_gcc5_4_build
      - pytorch_linux_trusty_pynightly_build
      - pytorch_linux_trusty_pynightly_test:
          requires:
            - pytorch_linux_trusty_pynightly_build
      - pytorch_linux_xenial_py3_clang5_asan_build
      - pytorch_linux_xenial_py3_clang5_asan_test:
          requires:
            - pytorch_linux_xenial_py3_clang5_asan_build
      - pytorch_linux_xenial_cuda8_cudnn7_py3_build
      - pytorch_linux_xenial_cuda8_cudnn7_py3_test:
          requires:
            - pytorch_linux_xenial_cuda8_cudnn7_py3_build
      - pytorch_linux_xenial_cuda8_cudnn7_py3_multigpu_test:
          requires:
            - pytorch_linux_xenial_cuda8_cudnn7_py3_build
      - pytorch_linux_xenial_cuda8_cudnn7_py3_NO_AVX2_test:
          requires:
            - pytorch_linux_xenial_cuda8_cudnn7_py3_build
      - pytorch_linux_xenial_cuda8_cudnn7_py3_NO_AVX_NO_AVX2_test:
          requires:
            - pytorch_linux_xenial_cuda8_cudnn7_py3_build
      - pytorch_short_perf_test_gpu:
          requires:
            - pytorch_linux_xenial_cuda8_cudnn7_py3_build
      - pytorch_doc_push:
          requires:
            - pytorch_linux_xenial_cuda8_cudnn7_py3_build
      - pytorch_linux_xenial_cuda9_cudnn7_py2_build
      - pytorch_linux_xenial_cuda9_cudnn7_py2_test:
          requires:
            - pytorch_linux_xenial_cuda9_cudnn7_py2_build
      - pytorch_linux_xenial_cuda9_cudnn7_py3_build
      - pytorch_linux_xenial_cuda9_cudnn7_py3_test:
          requires:
            - pytorch_linux_xenial_cuda9_cudnn7_py3_build
      - pytorch_linux_xenial_cuda9_2_cudnn7_py3_gcc7_build
      - pytorch_linux_xenial_cuda9_2_cudnn7_py3_gcc7_test:
          requires:
            - pytorch_linux_xenial_cuda9_2_cudnn7_py3_gcc7_build
      - pytorch_linux_xenial_cuda10_cudnn7_py3_gcc7_build

